version: '3'

services:
  app:
    build: .
    container_name: shop-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-shop:5432/shop
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - shop-network

  redis:
    image: redis:7.4-bookworm
    container_name: redis-server
    environment:
      REDIS_PASSWORD: redis
      REDIS_USER: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  postgres:
    image: postgres:17-alpine
    restart: always
    container_name: postgres-shop
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    networks:
      - shop-network
networks:
  shop-network:
    driver: bridge
