spring:
  application:
    name: 'ya-practicum-shop'
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    default-schema: public